# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Begi | 筆記"
weight = 1

# [zh-CN]
# languageName = "简体中文"
# languagedirection = "ltr"
# title = "Begi | 筆記"
# weight = 2
